export const CLEAR_CART = 'CLEAR_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const LOADING = 'LOADING'
export const DISPLAY_ITEMS = 'DISPLAY_ITEMS'
export const TOGGLE_AMOUNT = 'TOGGLE_AMOUNT'
